blank_issues_enabled: false
contact_links:
  - name: 📖 Smartsheet RM API Documentation
    url: https://developers.smartsheet.com/api/resource_management/openapi.md
    about: Official API documentation for Smartsheet Resource Management.
